### ISSUE TITLE
Bug- We can't be idiots and punch each other

### ISSUE THREAD

**Issue by CrowOfBourbon** [HypatiaStation/HypatiaStationDev#10]
**Description of the Bug**: Mobs can't punch, kick, lick, stomp or hump other mobs. 
**What were you doing when the bug happened**: Attempting to show Shaun Pavlov the glorious fox evolution by dick punching him. I moved, but I didn't actually attack him.
**What was the expected result of your actions**: Shaun injured from my fox fist of glory.
**What actually happened**: I just did the tango with him. (The attack move is there, but the actual attack is not)
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Go punch Shaun (or anyone, but Shaun works). 10/10 will do again.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Is borkededed. I mean, it's kinda medium, because it keeps us from chucklefucking, but it's high too because how can protect frm tator?

**Comment by Rohaneanew** [comment]
Testing in hotfix cycle 1.2

**Comment by Rohaneanew** [comment]
Solved and fixed. Enjoy punching.
