### ISSUE TITLE
Bug- petty Insignificant Hub Name problem

### ISSUE THREAD

**Issue by CrowOfBourbon** [HypatiaStation/HypatiaStationDev#12]
**Description of the Bug**: Name on the Hub in the new code isn't N.S.S Hypatia (or the N.T.T.S Hypatia
**What were you doing when the bug happened**: Well i noticed it earlier. Using this as a reminder for the Roho because our Skype is going off the chain with complaints ATM.
**What was the expected result of your actions**: I uhhh.. expected to find Hypatia.
**What actually happened**: I found the N.S.S Cyberion
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Throw up new code, see wrong name on hub.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Medium: How tha fuck we gonna be found? hehe <3

**Comment by Rohaneanew** [comment]
Done. Fixed in next Commit.
