### ISSUE TITLE
[Suggestion][Map] Atmospheric's Repiping

### ISSUE THREAD

**Issue by IxenKaldaka** [HypatiaStation/HypatiaStationDev#13]
**Description of the Bug**: Pipes were messed up, Read below for a detailed explanation from Master Atmos Tech Ixen Kaldaka. (Also find me on TS to help resolve the issue if needed)
**What were you doing when the bug happened**: Attempting to figure out why the pipes were screwed up.
**What was the expected result of your actions**: Pipes not to be screwed up
**What actually happened**: Pipes were screwed up
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Yes the pipes are still messed up
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Medium-High
**Detailed Explanation**
I am sure you devs expected atmos to be overly complex but I would like to assist in making it simple and a lot less messy. I would like to think I am knowledgeable in this area as all I every play literally is atmos tech. Also forgive the new unpainted pipes, there was no pipe painter in my department.(should be added)

**Distribution Loop**
*Remove the Heater- This has no point. The Temperature in all the chambers and pipes remain at 293.1 (20C) naturally. There is no use for a heater that heats a gas at 20C to 20C.
*Rework Piping to decrease eye sore and to clean up pipes. (See Picture) 
*Add Light Fixture
*Make the purple pipe leading to the scrubber under the tile while leaving the other pipe above. (like they did with the vent pipe)

![dispurs](https://cloud.githubusercontent.com/assets/13186487/8512114/c1d8c958-2302-11e5-93a6-9e8cbfe73865.png)

**Filtering Room**
*Move AI Requesting Holo Thingy
*Remove random wrench and crowbar on floor
*Replace small lights with large lights
*Repipe Pure lines and pumps.

![filter1](https://cloud.githubusercontent.com/assets/13186487/8512144/4a745a74-2304-11e5-844b-c968b4d578d8.png)

*Re Pipe the Nitrogen and Oxygen mixer to take up less floor space

![filter2](https://cloud.githubusercontent.com/assets/13186487/8512218/44f5e934-2307-11e5-9594-cecd55099774.png)

If anybody else finds any more efficient and more neat layout. Do note: This was done all ingame. With the map maker I'm sure much different more efficient layouts are possible.

**Comment by CrowOfBourbon** [comment]
As long as Atmos actually works, then you can expect it to stay the way it is map wise. This "modification" seems like it can be done ICly as a project, and I'm all for actually giving atmos techs something to do.
