### ISSUE TITLE
[Medium][Bug][Code/Map] Atmos Alerts for off-station Areas

### ISSUE THREAD

**Issue by IxenKaldaka** [HypatiaStation/HypatiaStationDev#14]
**Description of the Bug**: Upon server start Atmos has a Priority Alert for the Syndicate Outpost and MO19 Arrivals. 
**What were you doing when the bug happened**: Exploring
**What was the expected result of your actions**: I would expect there to be no Alerts on mission start. I would also expect the only alerts reported to Atmos be from the actual station, not from Synd. Outposts.
**What actually happened**: Alarms from two places Atmos tech cannot even access.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Same things happened two server restarts previously. 
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Low-Medium

**Comment by IxenKaldaka** [comment]
Update: After 30min or so, they disappeared. Not sure if an admin fixed this or if they fixed themselves.

**Comment by Rohaneanew** [comment]
Potentially a mapping, or a code thing. Will investigate further.

**Comment by CrowOfBourbon** [comment]
I know the reasoning behind this. It's an air alarm at one of the "away" missions and there really /isn't/ a way I can fix it map wise.

**Comment by Rohaneanew** [comment]
Updating: Because of the nature of this bug, I'm probably going to leave it as is. This can be looked at as an IC issue worth investigating by messaging CC. Closing and resolving.
