### ISSUE TITLE
[Low][Bug][Map]Disposal bay door don't open.

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaStationDev#15]
**Description of the Bug:** Disposal bay door don't open on trash eject.
**What were you doing when the bug happened:** I was trying to dump some trash to space
**What was the expected result of your actions:** Opening of bay door, dumping trash with mass driver, closing the door.
**What actually happened:**Mass driver working, but door doesn't open, trash is still on mass driver. 
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:** 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:** Low-Medium.

**Comment by CrowOfBourbon** [comment]
Fixed
