### ISSUE TITLE
[Low][Bug]Waste disposals stacking machine not working.

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaStationDev#16]
**Description of the Bug:** When sheets of material goes near stacking machine, they continue their way to mass driver.
**What were you doing when the bug happened:** I was looking at trash processing line in the Disposals, making some materials from trash.
**What was the expected result of your actions:** After being processed by crusher, i expected material sheets to be taken into stacking machine, stacked and released to secondary conveyor.
**What actually happened:** Material sheets was not picked up by stacker, continue their way to mass driver.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:** 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:** Low.

**Comment by CrowOfBourbon** [comment]
That area is a mappers worst nightmare. The stacking machine was removed. You'll just have to crush the stuff, let the belt cycle around, turn off the belt and manually pick up the material for now.
