### ISSUE TITLE
[Low][Bug][Code/Map] Delivery chute in Disposals sending items to wrong place.

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaStationDev#17]
**Description of the Bug:** Delivery chute in Disposals sending items just outside firing range.
**What were you doing when the bug happened:** Accidentally got drugged into Delivery Chute by conveyor.
**What was the expected result of your actions:** I expected to be thrown out from disposal outlet in Mailroom.
**What actually happened:**Found myself just outside firing range. 
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:** 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:** Low-Medium.

**Comment by Rohaneanew** [comment]
Hilarious. Will investigate further. This can be worked on at the same time as #32

**Comment by CrowOfBourbon** [comment]
Fixed.
