### ISSUE TITLE
[BUG] All weapons fire offset to the intended target/location.

### ISSUE THREAD

**Issue by JakeRamsay** [HypatiaStation/HypatiaStationDev#19]
**Description of the Bug**: All weapons fire offset to the target in weird ways.
**What were you doing when the bug happened**: Shooting a taser.
**What was the expected result of your actions**: It to fire in a straight line and hit the target.
**What actually happened**: It went left, missing the target and resulted in me getting stunsticked in the balls.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Every time.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: I'd say medium to high, since many players will have issues when trying to shoot someone with a taser as security.

**Comment by Fox-McCloud** [comment]
https://github.com/HypatiaStation/HypatiaStationDev/blob/master/code/modules/projectiles/gun.dm#L227

both instances of 544/2 need to be 480/2

**Comment by Rohaneanew** [comment]
Testing in hotfix 1.2

**Comment by Rohaneanew** [comment]
Solved and fixed. Still, yall need to get good at shooting.
