### ISSUE TITLE
Cooking System Non-Functional / Unknown Recipes

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#20]
Many recipes are non-functional. Tested with Meat Steak, Dough->Bun, and Meatballs. Of these, all dirtied the microwave. The meatballs from the Food Processor worked.

**Comment by CentComOp** [comment]
I will update this if I find any recipes that do in fact work. You also cannot slice meat into cutlets currently.

**Comment by CentComOp** [comment]
Boiled spaghetti works. Very confusing.

**Comment by CrowOfBourbon** [comment]
This isn't a code bug: This is a "We don't know the cooking code and need to learn it" bug. Please contact the Wiki team.
