### ISSUE TITLE
[High][Bug][Code] Basicmins have slightly borked perms.

### ISSUE THREAD

**Issue by SkullzMaster** [HypatiaStation/HypatiaStationDev#22]
**Description of the Bug**:  Basicmins cannot right-click and VV or Select Equipment. I know its possible for higher ranks though. We also cant use some of the Events in the Secret Panel because we dont have +Event. Also do not have the power to Mute people. We dont have the +Moderator
**What were you doing when the bug happened**:  Trying to "Roll the Dice"
**What was the expected result of your actions**:  I do not know..a dice roll?
**What actually happened**: It told me I didnt have permissions to do it.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**:  10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:  High

**Comment by SkullzMaster** [comment]
Also do not have the power to Mute people. We dont have the +Moderator

**Comment by SkullzMaster** [comment]
**Description of the Bug**:  Basicmins cannot right-click and VV or Select Equipment. I know its possible for higher ranks though. We also cant use some of the Events in the Secret Panel because we dont have +Event. Also do not have the power to Mute people. We dont have the +Moderator
**What were you doing when the bug happened**:  Trying to "Roll the Dice"
**What was the expected result of your actions**:  I do not know..a dice roll?
**What actually happened**: It told me I didnt have permissions to do it.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**:  10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:  High

**Comment by Rohaneanew** [comment]
Narrowed down problem to the +VarEdits flag.

**Comment by Rohaneanew** [comment]
Fixed in 1.4 Hotfix. Closing.
