### ISSUE TITLE
[Game Breaking][Bug][Code?/Map?] Tcomms randomly die

### ISSUE THREAD

**Issue by SkullzMaster** [HypatiaStation/HypatiaStationDev#23]
**Description of the Bug**:  Something about Tcomms just shutting off randomly. Unless there is an obvious reason and none of us knows it.
**What were you doing when the bug happened**:  Just playing. Tried to yell at people over Security channel and it wasn't working. Telecoms just randomly died and nothing but intercoms and station-bounced radios worked. This also occurred during Marine/ERT Training.
**What was the expected result of your actions**:  Talking on comms.
**What actually happened**:  Not talking on comms.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: ??/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Game Breaking

**Comment by Rohaneanew** [comment]
Potentially tracking cause due to events.

**Comment by TwistedAkai** [comment]
Just want to drop a note that Tcomms equipment has to stay cool and will shut down abruptly if it overheats. It's another possible cause to consider.

**Comment by CrowOfBourbon** [comment]
Tcomms is fine. An event fucked with it. We tested it and it ran a full shifts time fine. <3 Closing this.
