### ISSUE TITLE
[Medium][Map] Medbay machines

### ISSUE THREAD

**Issue by SkullzMaster** [HypatiaStation/HypatiaStationDev#24]
**Description of the Bug**:  Cryo tubes by body scanners are not mapped correctly. Freezer and the O2 platform are not properly set up. One of the sleepers is broken. (Console isn't facing the actual sleeper).
**What were you doing when the bug happened**:  Walking around Medical.
**What was the expected result of your actions**: N/A
**What actually happened**:  N/A
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:  Medium

**Comment by Rohaneanew** [comment]
Freezer and O2 are mapping things. Unsure about the sleeper, can someone please attempt to use that sleeper console to see if it's functional? May require icon state for reversed (assuming one exists, otherwise one will have to be coded/made)

**Comment by Rohaneanew** [comment]
The icon state for the alternate facing sleeper does exist, and it has a specific tag ("LEFT") that it should be using, along with direction 4. Not sure why it swaps back. Will investigate further.

**Comment by CrowOfBourbon** [comment]
Fixed, hopefully.
