### ISSUE TITLE
[Medium][Bug/Map?]Mining outpost machines don't work

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaStationDev#26]
**Description of the Bug:** Mining outpost smelting line machines not working at all.
**What were you doing when the bug happened:** Gathered some ore and was going to process it.
**What was the expected result of your actions:** Processing ores into nice materials.
**What actually happened:**All 3 of machines (unloading machine, material processor and stacking machine) wasn't taking any materials provided.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:** 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:** Low-Medium, there is cargo for ordering materials, but miners will not be happy.

**Comment by CrowOfBourbon** [comment]
Not a map error.

**Comment by Fox-McCloud** [comment]
This is because they require an input and output landmark---check out the Boxstation/Cyberiad map for reference.

Not really a bug; mapping error.

**Comment by CrowOfBourbon** [comment]
Hmmm I did look for that.... I'll check again.

**Comment by Fox-McCloud** [comment]
/obj/machinery/mineral/input
/obj/machinery/mineral/output 

are what you need.

**Comment by Rohaneanew** [comment]
Fixed and functional.
