### ISSUE TITLE
[Medium][Bug]Ore redemption machine isn't working

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaStationDev#27]
**Description of the Bug:** Ore redemption machine does nothing with ore.
**What were you doing when the bug happened:** Taken some ore to ore redemption machine for nice unusable points and easily processed materials.
**What was the expected result of your actions:** Processed materials and obtained points.
**What actually happened:**Nothing. Machine don't accept ore.. 
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:** 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:** Low, as i don' see any miner vendors, machine can be easily replaced with some wall.

**Comment by Rohaneanew** [comment]
Tagging this as a medium level bug regardless.

**Comment by Rohaneanew** [comment]
Referencing issue #30

**Comment by Spoopy11** [comment]
This might be a mapping issue to note, I think on the map, you need to have belts that feed ore into the designated input section of the map itself, which we might be missing. Works effectively the same as a smelter.

**Comment by CrowOfBourbon** [comment]
it is, I fixed the ones on the actual outpost, but this ore redemption machine on station has no belts.. I'l.. figure something out, even if it's removing it totally

**Comment by CrowOfBourbon** [comment]
The Ore redemp machine from cargo has been removed till I can figure out where I'm putting it and all of it's bloody belts
