### ISSUE TITLE
[Map] Research Shuttle

### ISSUE THREAD

**Issue by SkullzMaster** [HypatiaStation/HypatiaStationDev#29]
The research shuttle airlocks do not work. It is believed to be the lack of vents to properly change atmos. If that's not the case, then this is probably a bug.

**Comment by CrowOfBourbon** [comment]
Actually, airlocks don't cycle now. They open like.... you just click them with an access ID.

**Comment by CrowOfBourbon** [comment]
I was correct: Airlocks are fine there.
