### ISSUE TITLE
[Low][Bug][Map] Lack of GPS devices AND Bluespace Crystals in the Telescience lab

### ISSUE THREAD

**Issue by torger597** [HypatiaStation/HypatiaStationDev#31]
Byond Key: Torger597
Location of Bug: Telescience Lab
What sort of bug is it? (Atmospherics, Wiring etc): Items Mapping
Is there a special way to replicate this bug in the map?: No
Please attach a screenshot of the affected area:
![scrnshot1](https://cloud.githubusercontent.com/assets/8043130/8518167/29e4be78-238d-11e5-93bd-9ddda0bc5145.png)

**Comment by torger597** [comment]
Fixed template and title.

**Comment by CrowOfBourbon** [comment]
Fixed

**Comment by Fox-McCloud** [comment]
@CrowOfBourbon 

You've probably already added them, but there's meant to be 3 of them.
