### ISSUE TITLE
[Low][Bug][Map] Several spots are missing disposals piping

### ISSUE THREAD

**Issue by torger597** [HypatiaStation/HypatiaStationDev#32]
Byond Key: Torger597
Location of Bug: Security, Maintenance tunnel
What sort of bug is it? (Atmospherics, Wiring etc): Piping, Disposals
Is there a special way to replicate this bug in the map?: Restarting the server works.
Please attach a screenshot of the affected area(s):
![scrnshot2](https://cloud.githubusercontent.com/assets/8043130/8518383/293e2278-238f-11e5-83e6-1b6abac18caa.png)
![scrnshot1](https://cloud.githubusercontent.com/assets/8043130/8518384/2941e4ee-238f-11e5-8416-ad76c64ad822.png)

**Comment by torger597** [comment]
I'm standing next to the issue tile in both screen shots.

**Comment by Rohaneanew** [comment]
This can be worked on at the same time as #17

**Comment by CrowOfBourbon** [comment]
Fixed
