### ISSUE TITLE
[Suggestion] [Map?] ATMs / Money Transfers

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#33]
As far as I can tell, there is no means to transfer money from one play to the other save perhaps admin intervention. The re-adding of ATMs or another means of money transference would greatly increase the possibility of commerce RP.

**Comment by Rohaneanew** [comment]
This will be discussed by me and Tango probably not in Cycle 2, but potentially Cycle 3 (Friday the 17th)

**Comment by Fox-McCloud** [comment]
Just throwing this out there: Boxstation/Cyberiad is currently fully functional for ATMs at the moment, and there's definitely EFTPOSes in the code as well.

**Comment by CrowOfBourbon** [comment]
Easy fix, much wow. Will map shortly. The ATM's borked last shift because we spawned them in. If they're premapped, they will work.

**Comment by CrowOfBourbon** [comment]
ATM's added
