### ISSUE TITLE
[Low][Bug?][Map] Evidence Lockers are full of things at the start of the round.

### ISSUE THREAD

**Issue by Dude4Life** [HypatiaStation/HypatiaStationDev#35]
**Description of the Bug**: Evidence lockers are full of things when a shift/round starts, making security's job and organization in the lockers, more difficult.
**What were you doing when the bug happened**: So I went to the evidence locker room at the start of a round to stash some evidence or stuff, but when I first opened a locker, it had a lot of random things in it. The other lockers had the same issue. When I opened the evidence lockers at the start of the following rounds, they were full again.
**What was the expected result of your actions**: I was hoping to see the lockers empty and ready to store evidence.
**What actually happened**: The lockers were full of things, instead of being empty. Nobody else but me didn't use the evidence lockers neither. I had to clear out all the lockers and dispose of the things, before they could've been used more efficiently.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Low

**Comment by CrowOfBourbon** [comment]
Not a bug at all. it's just a spawner thing. Who cares? Gives you stuff to do.
