### ISSUE TITLE
[Medium][Bug][Map] Xenobio spawns with pet slimes, instead of breedable ones.

### ISSUE THREAD

**Issue by Grolarg** [HypatiaStation/HypatiaStationDev#37]
**Description of the Bug**: Pretty much as the title says. Xenobiology spawns with tamed "Pet Slimes" rather than the kind you can feed/grow/split
    **What were you doing when the bug happened**: Attempting to use the xenobiology lab
    **What was the expected result of your actions**: Being able to breed slimes
    **What actually happened**: Nothing, as the pet slimes are just pets
    **Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Every time
    **Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: At least medium, as Xenobio cannot be done currently from these.

**Comment by CrowOfBourbon** [comment]
Fixed
