### ISSUE TITLE
[Medium][Bug] AI Lawset is not Arcoss

### ISSUE THREAD

**Issue by Rohaneanew** [HypatiaStation/HypatiaStationDev#41]
**Description of the Bug**: AI Lawset doesn't switch to Arcos at the start of the round
**What were you doing when the bug happened**: An individual spawned in as the AI. They defaulted to Asimov
**What was the expected result of your actions**: Arcos would be selected and not Asimov
**What actually happened**: No Arcos.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:  Medium-High

**Comment by CentComOp** [comment]
For some reason the code is reading the default lawset as an empty custom lawset and going to the code falback which is hard set as Asimov. If the actual error cannot be found, could change the hard set Asimov to Arccos instead.

**Comment by Rohaneanew** [comment]
This is fixed. The custom lawset is set with the Arccos lawset. I'm going to however see if I can't tweak this a bit and get it to work.
