### ISSUE TITLE
[Low] Security Pod Pilot: MAP ISSUE

### ISSUE THREAD

**Issue by uoheinrich** [HypatiaStation/HypatiaStationDev#42]
Description of the Bug: The Pod for the Security Pod Pilot
What were you doing when the bug happened: The player spawned in to go to their pod. But no pod was found.
What was the expected result of your actions: Pod Pilot to go into space and kill the carp outside of the station.
What actually happened: There is no pod for the Pod Pilot.
Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself: 10/10
Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]: High, player unable to do job currently.

**Comment by Rohaneanew** [comment]
Will be fixed in Cycle 2. Sec pod pilot skill is likely going to at the very least, be closed for a moment.

**Comment by Rohaneanew** [comment]
Assigning this low priority, have slightly more important stuff to do.

**Comment by CrowOfBourbon** [comment]
This is not being mapped until we can stop chucklefucking with owl costumes and cars. End of discussion.
