### ISSUE TITLE
[Suggestion] [Map] Cooking Machinery

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#44]
Having initially thought it was a glitch, further investigation reveals that the issue with cooking is Paradise uses several cooking machines (Oven, Grill, etc) that are not on the map. Without these, cooking is severely limited.

List of machinery suggested:
Oven
Grill
Deep Fryer
Candy Maker

Addendum: There may be issues with space adding all these. Not sure how to fix that as space is already at a premium.

**Comment by Spoopy11** [comment]
As a note, if unaware, Para-code uses the TG crafting methods. Which involve piling your ingredients onto a table, then dragging the table to yourself to assemble the foot items.

**Comment by CrowOfBourbon** [comment]
Machinery added, as well as molds? I'm not sure what they're for, but you got 'em.
