### ISSUE TITLE
[Suggestion] [Map] Remove Pete

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#47]
Pete is a pet goat for the chef. Pete will, at no provocation, get an 'evil gleam' and start kicking the chef, potentially to death. He can be soothed if the chef constantly pets them in their presence.

I would highly recommend removing Pete for this reason, as it possible he will result in a number of rookie chef deaths or, best case, he gets turned into food/locked in Maint every round.

**Comment by Fox-McCloud** [comment]
He's insanely easy to kill, even if you have no weapons; he does 1-2 damage her hit.

In any event, the goat can also be milked, in case people didn't know. He also demolishes space vines in no time flat (dunno if you guys have random events turned on or not).

**Comment by Rohaneanew** [comment]
I'll adjust Pete's cooldown for becoming so angry, and if it still proves to be an issue, I'll just turn off his ability to be hostile entirely.

**Comment by CrowOfBourbon** [comment]
PETE STAYS! FOREVER! I might be able to vari edit his faction? Mebe. PETE STAYS! he needs a cigar and a sombrero.
