### ISSUE TITLE
Access issues with the air locks to the reserach shuttle dock

### ISSUE THREAD

**Issue by DJJohnny** [HypatiaStation/HypatiaStationDev#50]
The Research director does not have the proper access to the research shuttle dock airlocks

**Comment by Rohaneanew** [comment]
In the future use this form: http://hypatiastation.net/viewtopic.php?f=8&t=2649

**Comment by CrowOfBourbon** [comment]
Hilarious. I just bloody fixed these to have /all science access/. Are you /sure/? Because their access code IS research!

**Comment by CrowOfBourbon** [comment]
Fixed
