### ISSUE TITLE
[Suggestion][Map] Smart Fridge in the "Secure Lab" section of R&D

### ISSUE THREAD

**Issue by Grolarg** [HypatiaStation/HypatiaStationDev#52]
I feel like with the chemistry lab down in the Secure Lab, we really need a smart fridge to store chemicals. With the new chem code, there are even more base chemicals you need to make in large quantities, and it's super inconvenient to have to stack all the bottles on the small table we have.

**Comment by CrowOfBourbon** [comment]
granted. You owe me two cookies.
