### ISSUE TITLE
[Bug][Code][High] Rampant Brand Intelligence

### ISSUE THREAD

**Issue by CrowOfBourbon** [HypatiaStation/HypatiaStationDev#54]
Description of the Bug: One of our /lovely/ events is RBI, which is fine.. till it BLOWS HOLES IN EVERY PART OF THE SHIP THEN EATS THE CREW MEMBERS, THUS KILLING EVERYONE! It's bloody brilliant but it should be toned down a bit. Cigarette machines are OP as fuck, yo.
What was the expected result of your actions: Well first of all, /I/ didn't do it, the random events did. Second of all, I didn't expect coffee machines to be BLOWIN' HOLES IN ME SHIP!
What actually happened: Chaos. utter fucking chaos. The machines blew holes where they were, then ran around trying to eat people. They killed a lot of crew, actually.
Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself: 10/10
Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]: High, only becomes an issue if attempting to do an event.

**Comment by Fox-McCloud** [comment]
Lol. Not a bug, but you may want to consider removing this event from your rotation given the type of server Hypatia is.This is how rampant brand is meant to function.

**Comment by CentComOp** [comment]
According to the code, this event is removed from rotation as of the latest patch. Will need an Admin to confirm it is no longer possible to occur.

**Comment by Rohaneanew** [comment]
This was not removed completely, however I did remove them randomly exploding holes straight through the station. Should help against the event. They're still obnoxious and will shoot things at you though.

Note: They will still explode.
