### ISSUE TITLE
Server Attack Logs. 

### ISSUE THREAD

**Issue by Shadow7889** [HypatiaStation/HypatiaStationDev#55]
Server is lacking attack logs for staff. This is a concern.

**Comment by TwistedAkai** [comment]
Are you referring to Variables, the logs sent to chat, or the Attack log file?

**Comment by CrowOfBourbon** [comment]
the logs sent to the chat.

**Comment by Fox-McCloud** [comment]
There's an option to turn them on or off for yourself. You can also VV attack logs on mobs and such---as for an external file? Well, "show server attack logs" does nothing, currently, but attack logs ARE stored in the "server log"--thought it is a bit more info to sift through.

**Comment by Rohaneanew** [comment]
Not touching this until the above is answered.

**Comment by CrowOfBourbon** [comment]
Until what above is answered? I answered it "The logs sent to the chat."

We can't see self-harm attack logs, or other random as fuck attacks.

**Comment by Fox-McCloud** [comment]
I believe most self-harm logs were removed by us because it's spammy and we didn't want people who were just casually suiciding to be spamming up logs of legit grief.
