### ISSUE TITLE
Vulsarian's are Failsarians

### ISSUE THREAD

**Issue by CrowOfBourbon** [HypatiaStation/HypatiaStationDev#6]
**Description of the Bug**: Well the Vulsarian race just breaks everything. They don't have a body color, and if you save the slot, it'll fuck over your ability to even open the setup panel. You can't change their face or hairstyle and you can't change their color either.
**What were you doing when the bug happened**: Attempting to test the Vulsarian race. 
**What was the expected result of your actions**: Obviously I expected my setup to work.
**What actually happened**: I broke OTD T.T
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Attempt to set up Vulsarian: Fail miserably. 
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Pretty damn big. If the race is attempted, it'll keep you from actually setting up characters.

Notes: they worked when I last tested the apartments. here's a SS of the no body color Vulsarian: http://i.imgur.com/021WJft.png

**Comment by Rohaneanew** [comment]
Done and fixed.
