### ISSUE TITLE
Shard/Cross runtime error

### ISSUE THREAD

**Issue by Spoopy11** [HypatiaStation/HypatiaStationDev#61]
Description of the Bug: When walking over glass-shards, a proc is called to apply damage to feet. When there are no feet present on a person applicable to be damaged, it throws a runtime. Couple this with a couple dozen shards of glass, it creates lags, and a thousand runtimes 
What were you doing when the bug happened: On server when it began. After, tested locally with the newest Dev-branch-build.
What was the expected result of your actions: For the server not to poop itself, curl up, and cry.
What actually happened: The server curled up, pooped, and cried.
Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself: 10/10 when the code picks the correct limb OR, 10/10 when both feet are removed and the person/human/person is dragged over a shard.
Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]: Game breaking

I've no experience in Byond coding, but a simple check could possibly eliminate the bug;
Currently the code calls two IF statements, check if a robot, if so, return and end proc.
If non-synthetic mob, then check if have shoes, or items that cover the shoe slot. IF not, apply damage - this is where I believe the runtime occurs. A simple check, or conditional statement to check if the limb is present will hopefully stop it - good code to apply to the other limb, or not at all if both aren't.

Hope it helps!

**Comment by Fox-McCloud** [comment]
will be fixed once everything is synced.

**Comment by CentComOp** [comment]
Issue appears to be fixed as of latest patch.
