### ISSUE TITLE
[Bug][Map] Invisible Engineering Tape

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#62]
**Description of the Bug**: There is invisible Engineering tape blocking access to the Bazaar.
**What were you doing when the bug happened**: Trying to enter the Bazaar.
**What was the expected result of your actions**: Cross through the doors unimpeded.
**What actually happened**: Stopped, had to alt-click the tile and destroy invisible tape.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: 10/10
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:  Low=Medium

**Comment by Rohaneanew** [comment]
This is intentional, namely because the Bazaar isn't finished. Not sure why the tape is invisible though.

**Comment by CrowOfBourbon** [comment]
I mapped the wrong tape and I'm nine shades of fucking done with mapping since Tcomms won't stop being a rude cunt.

So the invi tape stays. It's not hurting anything.

**Comment by CentComOp** [comment]
The tape is still there AND invisible as of the latest patch. Just noting, not too important as Crow said.
