### ISSUE TITLE
[Bug][Code] Making Food out of Inedible Items

### ISSUE THREAD

**Issue by CentComOp** [HypatiaStation/HypatiaStationDev#64]
**Description of the Bug**: Cooking using the oven can accept ANY item as an ingredient.
**What were you doing when the bug happened**: Cooking in the kitchen, accidentally stuck a candy mold in the oven.
**What was the expected result of your actions**: It would be denied.
**What actually happened**: I got " bread"
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: 10/10, tried with a chef hat and fork.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Low

**Comment by Rohaneanew** [comment]
This isn't a bug, it's a feature of Paradise's cooking system. Happy cooking!!
