### ISSUE TITLE
Surgery

### ISSUE THREAD

**Issue by Aneddu** [HypatiaStation/HypatiaStationDev#65]
**Description of the Bug**:-The Bone Gel, Bone Setter, and Fix-O-Vein don't spawn in the surgery room like they should.
**What were you doing when the bug happened**:-Preforming surgery
**What was the expected result of your actions**:-That I could preform surgery
**What actually happened**:-It was halted until I PMed about it because I didnt have all the proper tools required.
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**:- 10/10 I would imagine as there are others who noticed the same issue
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:- I would say High, personally. While the admins CAN spawn the items in the issue is what if there are no admins on at the time and you have to fix a broken arm or some other broken bone? Then you can't because the items are missing and this can cause an issue.

**Comment by CrowOfBourbon** [comment]
I literally just put these in.
