### ISSUE TITLE
[High][Bug][MAP] Revolver with live round in the Club

### ISSUE THREAD

**Issue by IxenKaldaka** [HypatiaStation/HypatiaStationDev#7]
**Description of the Bug**: There is a Russian Revolver in the Club with one live round that can kill people.
**What were you doing when the bug happened**: Exploring
**What was the expected result of your actions**: The gun would fire
**What actually happened**: The gun fired
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Once, as there is one bullet in the revolver.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: High due to killing people is bad.

**Comment by Rohaneanew** [comment]
Assigning Crow to this, as it's a mapping issue.

**Comment by CrowOfBourbon** [comment]
Gambling spawner has been removed.
