### ISSUE TITLE
[Low][bug][map]Vending machine's unable to process payment

### ISSUE THREAD

**Issue by Spoopy11** [HypatiaStation/HypatiaStationDev#8]
Description of the Bug: Vending machines are incapable of processing payment, see attached: 
What were you doing when the bug happened: http://i.imgur.com/Wa0Phdu.png

What was the expected result of your actions: Payment to be processed from card, item to be dispensed. 

What actually happened: Attempted to buy items from various vendors, did not process. http://i.imgur.com/Wa0Phdu.png

Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself: 10/10

Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]: low-medium - can stop people from buying food.

**Comment by Rohaneanew** [comment]
Reason for this is due to a lack of Account Database on the map. Assigning this to Tango.

**Comment by CrowOfBourbon** [comment]
account database monitor added. I won't close this till we see if it resolves the issue.

**Comment by Rohaneanew** [comment]
Fixed, closing.
