### ISSUE TITLE
[Low][Suggestion][Map] Atmospheric's lack of tools/equipment/Areas

### ISSUE THREAD

**Issue by IxenKaldaka** [HypatiaStation/HypatiaStationDev#9]
**Description of the Bug**: Is if possible to give atmospherics engineering webbing (to hold more equipment in our jumpsuits), welding goggles, and flashlights in our lockers? Also if we could have access to the normal engineer's area so we can have access to metals, glass, and other equipment to deal with station holes from explosions? Also we could use a Pipe Painter.
**What were you doing when the bug happened**: Exploring
**What was the expected result of your actions**: Finding these things
**What actually happened**: I didn't find these things
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: You would still not find these things.
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: Low

**Comment by Rohaneanew** [comment]
This is a suggestion, not a bug.

**Comment by Rohaneanew** [comment]
@CrowOfBourbon Make a small stockpile of metal, plasteel, glass in atmos for them, 2 stacks each. Include welding goggles in lockers flashlights as well. Post when this is done. 

As far as the rest of the stuff goes, you're an Atmos Tech, not an engineer. They're two different jobs.

**Comment by IxenKaldaka** [comment]
Can you add a pipe painter to that list of stuff to add to atmos? I have been unable to fine one.

**Comment by Rohaneanew** [comment]
I'm not sure if pipe painters are a part of paraccode. Will be on the lookout.

**Comment by IxenKaldaka** [comment]
Thank you for looking into it.

**Comment by Fox-McCloud** [comment]
There are pipe painters. There's also webbing vets, but we killed them all off on the map/in lockers because of how OP they are; you can definitely still find them in the codebase though.

**Comment by CrowOfBourbon** [comment]
Pipe painter added. Everything else is /literally/ already in there for Christs sake. There's glass, metal and welding helmets on the tables. 

Please /look/ before making github requests.
